---
#TODO: fix for not use ansible_python_interpreter
- name: "Configure bastion from when OpenShift will be installed"
  hosts: localhost
  roles:
    - role: configure_bastion
      vars:
        ansible_python_interpreter: "{{ python_interpreter | default(None) }}"

  environment: "{{ openshift_proxy | default(omit) }}"
